### ISSUE TITLE
Usage in custom problems/datasets

### ISSUE THREAD

**Issue by shivam-chandhok** [icemiliang/pyvot#28]
Hi,

I was going through the paper "Regularized Wasserstein Means for Aligning Distributional Data" and wanted to know how can these losses be incorporated for distribution alignment problems on custom datasets.

Thank you

**Comment by icemiliang** [comment]
Hello,

I don't know exactly what you wanted to incorporate OT into. Regardlessly, a simple way is using (regularized) OT to get the correspondences between samples and then build an MSE-like loss for your solver. If you meant directly using OT to align your data, you can try the demo code if you haven't. Thanks.

**Comment by icemiliang** [comment]
Closing the issue for now. Please reopen it if needed.
