### ISSUE TITLE
Does VOTAP support high-dimensional data?

### ISSUE THREAD

**Issue by lzhzju** [icemiliang/pyvot#31]
The demos of VOTAP seem to be experimenting with 2D data. Does VOTAP support high-dimensional data?

**Comment by icemiliang** [comment]
Honestly I'm not sure. In the _Regularized Wasserstein Means for Aligning Distributional Data_ paper, I used Decaf-fc6 and Decaf-fc7 features which have 4,096 dimensions, but those are pretty sparse samples, they can't represent the volume of the cell. If you can directly compute or approximate the volume/area of the cell in high-dimensional spaces, then the algorithm should work properly, but I doubt the volume in high-dimensional spaces makes much sense. Let me know if you have further questions.

**Comment by icemiliang** [comment]
Let me know if there's any follow-ups. Closing the problem for now.
